#spring:
#  application:
#    name: hello-spring-cloud-admin
#  zipkin:   #加入zipkin链路追踪
#    base-url: http://localhost:9411
#
#
#server:
#  port: 8084
#
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: ["health","info"]
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: YKR-admin
      label: master
      profile: prod